 # TODO rename to DISTRO with DIST in .travis.yaml
 - name: 'DIST'
   value: 'centos-8 '
 - name: 'TARGETS'
   value: 'storage tests'
# TODO use better flag e.g. OVIRT_CI, keeping travis flag until we resolve all failures skipped on travis
 - name: 'TRAVIS_CI'
   value: 'true'
 - name: 'PYLINT_JOBS'
   value: 2
 - name: 'NETWORK_COVERAGE'
   value: 38
